[env]
RUST_LIB_PATH = { source = "${CARGO_MAKE_RUST_TARGET_OS}", default_value = "", mapping = {"linux" = "./target/release/librust_ext.so", "macos" = "./target/release/librust_ext.dylib", "windows" = "./target/release/rust_ext.dll" } }
RUST_LIB_EXT = { source = "${CARGO_MAKE_RUST_TARGET_OS}", default_value = "so", mapping = { "windows" = "pyd" } }

[tasks.all]
dependencies = ["build", "move"]

[tasks.re]
dependencies = ["clean", "build", "move"]

[tasks.move]
script_runner = "@shell"
script = '''
echo Detected platform : $CARGO_MAKE_RUST_TARGET_OS\nMoving file to correct folder
mv $RUST_LIB_PATH ./src/PyInterface/rust_ext.$RUST_LIB_EXT
'''

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.clean]
dependencies = ["remove"]
command = "cargo"
args = ["clean"]

[tasks.remove]
script_runner = "@shell"
script = '''
echo Remove dynamic library
rm ./src/PyInterface/rust_ext.$RUST_LIB_EXT
'''
