[tasks.all]
dependencies = ["build", "move"]

[tasks.re]
dependencies = ["remove", "clean", "all"]

[tasks.move]
script_runner = "@shell"
script = '''
echo Platform detected: Macos
mv ./target/release/librust_ext.dylib ./src/PyInterface/rust_ext.so
'''

[tasks.move.windows]
script_runner = "@shell"
script = '''
echo Platform detected: Windows
mv ./target/release/rust_ext.dll ./src/PyInterface/rust_ext.pyd
'''

[tasks.move.linux]
script_runner = "@shell"
script = '''
echo Platform detected: Linux
mv ./target/release/librust_ext.so ./src/PyInterface/rust_ext.so
'''

[tasks.build]
command = "cargo"
args = ["build", "--release"]


[tasks.test]
command = "cargo"
args = ["test"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.remove]
script_runner = "@shell"
script = '''
echo Remove dynamic library
rm ./src/PyInterface/rust_ext.so
'''
